/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BookmarksImport } from './routes/bookmarks'
import { Route as IndexImport } from './routes/index'
import { Route as PlaylistIndexImport } from './routes/playlist.index'
import { Route as ChannelIndexImport } from './routes/channel.index'
import { Route as PlaylistPlaylistIdImport } from './routes/playlist.$playlistId'
import { Route as ChannelChannelIdImport } from './routes/channel.$channelId'

// Create/Update Routes

const BookmarksRoute = BookmarksImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistIndexRoute = PlaylistIndexImport.update({
  id: '/playlist/',
  path: '/playlist/',
  getParentRoute: () => rootRoute,
} as any)

const ChannelIndexRoute = ChannelIndexImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistPlaylistIdRoute = PlaylistPlaylistIdImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRoute,
} as any)

const ChannelChannelIdRoute = ChannelChannelIdImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksImport
      parentRoute: typeof rootRoute
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdImport
      parentRoute: typeof rootRoute
    }
    '/channel/': {
      id: '/channel/'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelIndexImport
      parentRoute: typeof rootRoute
    }
    '/playlist/': {
      id: '/playlist/'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/channel': typeof ChannelIndexRoute
  '/playlist': typeof PlaylistIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/channel': typeof ChannelIndexRoute
  '/playlist': typeof PlaylistIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/channel/': typeof ChannelIndexRoute
  '/playlist/': typeof PlaylistIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/channel/$channelId'
    | '/playlist/$playlistId'
    | '/channel'
    | '/playlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/channel/$channelId'
    | '/playlist/$playlistId'
    | '/channel'
    | '/playlist'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/channel/$channelId'
    | '/playlist/$playlistId'
    | '/channel/'
    | '/playlist/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  ChannelIndexRoute: typeof ChannelIndexRoute
  PlaylistIndexRoute: typeof PlaylistIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  ChannelIndexRoute: ChannelIndexRoute,
  PlaylistIndexRoute: PlaylistIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bookmarks",
        "/channel/$channelId",
        "/playlist/$playlistId",
        "/channel/",
        "/playlist/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bookmarks": {
      "filePath": "bookmarks.tsx"
    },
    "/channel/$channelId": {
      "filePath": "channel.$channelId.tsx"
    },
    "/playlist/$playlistId": {
      "filePath": "playlist.$playlistId.tsx"
    },
    "/channel/": {
      "filePath": "channel.index.tsx"
    },
    "/playlist/": {
      "filePath": "playlist.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
