/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistIndexRouteImport } from './routes/playlist.index'
import { Route as ChannelIndexRouteImport } from './routes/channel.index'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'

const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIndexRoute = PlaylistIndexRouteImport.update({
  id: '/playlist/',
  path: '/playlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelIndexRoute = ChannelIndexRouteImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/channel/': typeof ChannelIndexRoute
  '/playlist/': typeof PlaylistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/channel': typeof ChannelIndexRoute
  '/playlist': typeof PlaylistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/channel/': typeof ChannelIndexRoute
  '/playlist/': typeof PlaylistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/channel/$channelId'
    | '/playlist/$playlistId'
    | '/channel/'
    | '/playlist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/channel/$channelId'
    | '/playlist/$playlistId'
    | '/channel'
    | '/playlist'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/channel/$channelId'
    | '/playlist/$playlistId'
    | '/channel/'
    | '/playlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  ChannelIndexRoute: typeof ChannelIndexRoute
  PlaylistIndexRoute: typeof PlaylistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/': {
      id: '/playlist/'
      path: '/playlist'
      fullPath: '/playlist/'
      preLoaderRoute: typeof PlaylistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/': {
      id: '/channel/'
      path: '/channel'
      fullPath: '/channel/'
      preLoaderRoute: typeof ChannelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  ChannelIndexRoute: ChannelIndexRoute,
  PlaylistIndexRoute: PlaylistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
